name: Run on Merge to Main

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Trigger on push to the 'main' branch

jobs:
  run-on-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a simple script
        run: |
          echo "Code has been merged into the main branch!"
